# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('times', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('times', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dailylimits',
            unique_together=set([('id', 'key')]),
        ),
    ]
