# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilimiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylimits',
            name='time_left',
            field=models.IntegerField(default=1476950224.0693767),
        ),
    ]
